### ISSUE TITLE
Нет гарантий, что мы влезем в эту константу

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#1]
https://github.com/NikolayZakharevich/bigint/blob/4d37c074be74ff752ea703489e9427da0b2febab/main.c#L8

**Comment by NikolayZakharevich** [comment]
Теперь влезем
https://github.com/NikolayZakharevich/bigint/blob/bd5ac57ab3e59e59bbd6af2c9ee67011ccb6f226/main.c#L34
