### ISSUE TITLE
Здесь не то поведение котоорые вы ожидаете, по факту оба часла буду ссылаться на одну облать памяти по digits

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#12]
https://github.com/NikolayZakharevich/bigint/blob/326f447bae7cd8077f9582ca91e8acc8786ed4f2/bigint.c#L210

**Comment by NikolayZakharevich** [comment]
Да, я уже заметил, когда делал остальные функции, забыл убрать это в модуле
