### ISSUE TITLE
метод упадет если сюда NULL приедет

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#13]
https://github.com/NikolayZakharevich/bigint/blob/326f447bae7cd8077f9582ca91e8acc8786ed4f2/bigint.c#L508

**Comment by NikolayZakharevich** [comment]
Я так понял, что здесь глубокая проблема. В C нельзя узнать инициализировалось ли поле структуры, то есть в такой ситуации не получится сделать проверку, лежит ли что-то в s.something.
![image](https://user-images.githubusercontent.com/29925226/34463405-d74a7118-ee63-11e7-9489-283b5154c8fe.png) 
Поэтому я оставил в деструкторе только очистку памяти
