### ISSUE TITLE
C одно стороны мы можем не влезть в этот размер, с другой если увеличть значнение, то будет не эффективное исользование памяти

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#2]
https://github.com/NikolayZakharevich/bigint/blob/4d37c074be74ff752ea703489e9427da0b2febab/bigint.h#L10

**Comment by NikolayZakharevich** [comment]
исправлено
https://github.com/NikolayZakharevich/bigint/blob/477f6fa8a70debea1713a8c54e8fa98a26734abc/bigint.h#L10
