### ISSUE TITLE
В этом месте падение, если строка из одного символа '-'

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#4]
https://github.com/NikolayZakharevich/bigint/blob/4d37c074be74ff752ea703489e9427da0b2febab/bigint.c#L58

**Comment by NikolayZakharevich** [comment]
isNumber больше не пропускает это
https://github.com/NikolayZakharevich/bigint/blob/bd5ac57ab3e59e59bbd6af2c9ee67011ccb6f226/bigint.c#L15
