### ISSUE TITLE
Не очень понял глубокого смысла двигаться по несколько символов, а не по одному 

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#6]
https://github.com/NikolayZakharevich/bigint/blob/4d37c074be74ff752ea703489e9427da0b2febab/bigint.c#L79

**Comment by NikolayZakharevich** [comment]
согласен, по одному выглядит логичнее
https://github.com/NikolayZakharevich/bigint/blob/bd5ac57ab3e59e59bbd6af2c9ee67011ccb6f226/bigint.c#L87
