### ISSUE TITLE
В вашем случае "00017" > "239"

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#7]
https://github.com/NikolayZakharevich/bigint/blob/4d37c074be74ff752ea703489e9427da0b2febab/bigint.c#L102

**Comment by NikolayZakharevich** [comment]
Конструктор больше не создает чисел с лидирующими нулями, также в функциях появилась проверка на это
https://github.com/NikolayZakharevich/bigint/blob/bd5ac57ab3e59e59bbd6af2c9ee67011ccb6f226/bigint.c#L120
