### ISSUE TITLE
Не очень понял идею с BASE_LENGHT 

### ISSUE THREAD

**Issue by ahvastunov-itmo** [NikolayZakharevich/bigint#9]
https://github.com/NikolayZakharevich/bigint/blob/326f447bae7cd8077f9582ca91e8acc8786ed4f2/bigint.c#L73

**Comment by NikolayZakharevich** [comment]
Если вы про +5, то это небольшая страховка, могу убрать. Деление на BASE_LENGTH дает количество цифр в представлении числа в системе счисления с основанием BASE -> количество памяти, которую нужно выделить
